"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# JWT authentication views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Router for automatically generating API routes
from rest_framework.routers import DefaultRouter

# ViewSets for the calendar app
from api.calendar_app.views import HolidayViewSet, EventViewSet, TaskViewSet


# API ROUTER SETUP
# Create a router to handle REST API routes
router = DefaultRouter()

# Register API endpoints with the router
router.register("holidays", HolidayViewSet, basename="holiday")
router.register("events", EventViewSet, basename="event")
router.register("tasks", TaskViewSet, basename="task")


urlpatterns = [
    # Django admin panel
    path('admin/', admin.site.urls),

    # Authentication endpoints (JWT)
    path("api/auth/login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/auth/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    
    # Include all API routes generated by the router
    path('api/', include(router.urls)),

    # Redirect root URL (/) to the API root
    path('', RedirectView.as_view(url='/api/', permanent=False)),  # <-- redirect root to /api
]
