# Generated by Django 6.0.1 on 2026-07-25 11:52

import api.calendar_app.utils.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_bs',
            field=models.CharField(max_length=10, validators=[api.calendar_app.utils.dates.validate_bs_date]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_bs',
            field=models.CharField(max_length=10, validators=[api.calendar_app.utils.dates.validate_bs_date]),
        ),
    ]
